export const tools = Object.freeze([
  { file: "/age.html", name: "Age Calculator", icon: "⌁", category: "Calculators", description: "Calculate an exact age and time until the next birthday." },
  { file: "/bmi-calculator.html", name: "BMI Calculator", icon: "♡", category: "Calculators", description: "Estimate body mass index with metric or imperial units." },
  { file: "/loan-calculator.html", name: "Loan Calculator", icon: "%", category: "Calculators", description: "Estimate monthly payments, total interest, and loan cost." },
  { file: "/percentage-calc.html", name: "Percentage Calculator", icon: "%", category: "Calculators", description: "Solve percentage, change, increase, and decrease questions." },
  { file: "/tip-calculator.html", name: "Tip Calculator", icon: "÷", category: "Calculators", description: "Calculate tips and split a bill between people." },
  { file: "/base64.html", name: "Base64 Encoder", icon: "64", category: "Developer", description: "Encode and decode text or files in Base64." },
  { file: "/code-beautifier.html", name: "Code Beautifier", icon: "{ }", category: "Developer", description: "Format JavaScript, HTML, CSS, and JSON." },
  { file: "/hash-generator.html", name: "Hash Generator", icon: "#", category: "Developer", description: "Generate common hashes for text and local files." },
  { file: "/json-formatter.html", name: "JSON Formatter", icon: "[ ]", category: "Developer", description: "Validate, format, and minify JSON data." },
  { file: "/markdown-preview.html", name: "Markdown Preview", icon: "M↓", category: "Developer", description: "Write Markdown with a live rendered preview." },
  { file: "/regex-tester.html", name: "RegEx Tester", icon: ".*", category: "Developer", description: "Test regular expressions with live match highlighting." },
  { file: "/url-tool.html", name: "URL Encoder", icon: "↗", category: "Developer", description: "Encode or decode URLs and URI components." },
  { file: "/color-converter.html", name: "Color Converter", icon: "◒", category: "Design", description: "Convert between HEX, RGB, HSL, and CMYK." },
  { file: "/gradient-generator.html", name: "Gradient Generator", icon: "◐", category: "Design", description: "Build linear and radial CSS gradients visually." },
  { file: "/box-shadow-generator.html", name: "Shadow Generator", icon: "□", category: "Design", description: "Tune CSS box shadows and copy the result." },
  { file: "/qrcode.html", name: "Advanced QR Studio", icon: "▦", category: "Media", description: "Create branded QR codes for links, contacts, audio, Wi-Fi, and text." },
  { file: "/image-compressor.html", name: "Image Compressor", icon: "▧", category: "Media", description: "Reduce image file sizes locally in the browser." },
  { file: "/pdf-merger.html", name: "PDF Merger", icon: "PDF", category: "Media", description: "Combine multiple PDF files into one document." },
  { file: "/pixformat.html", name: "PixFormat", icon: "PX", category: "Media", description: "Explore the PixFormat image conversion project." },
  { file: "/text-to-speech.html", name: "Text to Speech", icon: "◖", category: "Media", description: "Read text aloud with browser speech controls." },
  { file: "/currency-converter.html", name: "Currency Converter", icon: "$", category: "Converters", description: "Convert between major fiat and digital currencies." },
  { file: "/file-size-calc.html", name: "File Size Converter", icon: "KB", category: "Converters", description: "Convert bytes, KB, MB, GB, and TB." },
  { file: "/unit-converter.html", name: "Unit Converter", icon: "↔", category: "Converters", description: "Convert length, weight, temperature, area, and volume." },
  { file: "/lorem-ipsum.html", name: "Lorem Ipsum", icon: "¶", category: "Text", description: "Generate placeholder paragraphs, sentences, or words." },
  { file: "/password.html", name: "Password Generator", icon: "✦", category: "Text", description: "Create a personalized password from memorable inputs." },
  { file: "/to-do.html", name: "To-Do List", icon: "✓", category: "Productivity", description: "Keep a lightweight task list in the browser." },
  { file: "/youtube.html", name: "YouTube Live Counter", icon: "▶", category: "Live Data", description: "Track live public statistics for a YouTube channel." },
  { file: "/github.html", name: "GitHub Repo Viewer", icon: "GH", category: "Live Data", description: "Browse public GitHub profile and repository data." },
  { file: "/binance.html", name: "Strategy Tester", icon: "↗", category: "Live Data", description: "Experiment with historical crypto strategy parameters." },
  { file: "/acrossboard.html", name: "AcrossBoard", icon: "AB", category: "Projects", description: "Explore the cross-device clipboard experiment." },
  { file: "/sheekryptor.html", name: "SheeKryptor", icon: "SK", category: "Projects", description: "Read about the desktop encryption toolkit project." },
]);

export const categories = Object.freeze(["All", ...new Set(tools.map((tool) => tool.category))]);
