name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - run: node --version
    - run: npm --version
    - run: npm cache clean --force
    - run: rm -rf node_modules package-lock.json
    - run: npm install --verbose
    - run: npm install
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        cache-dependency-path: '**/package-lock.json' # THIS PATTERN did the trick for me.
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: node ./assets/js/server.js  # Specify the path to server.js
    - run: npm test
